# Generated by Django 5.1.6 on 2025-02-11 22:19

import django.db.models.deletion
import url_managements.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Date and time when object is created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Date and time when object is updated",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        verbose_name="The URL where the redirect will lead"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=True,
                        verbose_name="Restrict access to unauthenticated users?",
                    ),
                ),
                (
                    "redirect_identifier",
                    models.CharField(
                        default=url_managements.utils.generate_redirect_identifier,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Short unique identifier for redirect rule",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redirect_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner of the redirect rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Redirect rule",
                "verbose_name_plural": "Redirect rules",
                "db_table": "redirect_rules",
            },
        ),
    ]
